controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# ajouter_au_panier:
#   path: /produits/{id}/add
#   controller: App\Controller\PanierController::ajouterProduit
#   methods: ['POST']
  
# panier_show:
#   path: /panier/show/cart/{user}
#   controller: App\Controller\PanierController::afficherPanier
